### ISSUE TITLE
Archive stops on encryption error "nio.exceptions.EncryptionError: Mismatched SHA-256 digest."

### ISSUE THREAD

**Issue by arthurlutz** [russelldavies/matrix-archive#2]
```
[snip]
Fetching room messages and writing to disk...
Traceback (most recent call last):
  File "matrix-archive.py", line 172, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "matrix-archive.py", line 161, in main
    await write_event(client, room, f, event)
  File "matrix-archive.py", line 92, in write_event
    crypto.attachments.decrypt_attachment(
  File "/home/arthur/.virtualenvs/matrix/lib/python3.8/site-packages/nio/crypto/attachments.py", line 55, in decrypt_attachment
    raise EncryptionError("Mismatched SHA-256 digest.")
nio.exceptions.EncryptionError: Mismatched SHA-256 digest.
``

Maybe the exception should be caught and the script could carry on ?

**Comment by russelldavies** [comment]
I had intentionally done no error handling as I wanted to see what exceptions I was getting in practice and what would be the best way to handle them. I haven't seen that one myself but it seems fine to skip over.
