### ISSUE TITLE
AttributeError: 'DownloadError' object has no attribute 'body'

### ISSUE THREAD

**Issue by xdrie** [russelldavies/matrix-archive#21]
```
Traceback (most recent call last):
  File "/home/user/projects/matrix-archive/matrix-archive.py", line 219, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/user/projects/matrix-archive/matrix-archive.py", line 197, in main
    await write_room_events(client, room)
  File "/home/user/projects/matrix-archive/matrix-archive.py", line 181, in write_room_events
    await write_event(client, room, f, event)
  File "/home/user/projects/matrix-archive/matrix-archive.py", line 102, in write_event
    media_data = await download_mxc(client, event.url)
  File "/home/user/projects/matrix-archive/matrix-archive.py", line 134, in download_mxc
    return response.body
AttributeError: 'DownloadError' object has no attribute 'body'
```

When exporting a particular room.

**Comment by ColonisationCaptain** [comment]
This issue has been fixed in the latest commit.
